variables:
  workingDir: $(Build.Repository.LocalPath)/azuredatafactory/src
  serviceConnection: 'AzureServiceConnection'
  subscriptionId: '8308f340-4d69-4343-a5af-5437a6121b15'
  resourceGroupName: 'red-adfdemo-rg-dev'
  dataFactoryName: 'red-demo-adf-dev'
  dataFactoryResourceId: 