trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azuredatafactory
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDir: $(Build.Repository.LocalPath)/azuredatafactory/src
  serviceConnection: 'QuickStartTemplates-AzureServiceConnection'
  subscriptionId: $(SUBSCRIPTIONID)
  resourceGroupPartialName: 'red-adfdemo-rg'
  dataFactoryPartialName: 'red-demo-adf'
  locationName: 'southcentralus'

stages:
  - stage: build
    variables:
      resourceGroupName: $(resourceGroupPartialName)-dev
      dataFactoryName: $(dataFactoryPartialName)-dev
    jobs:
      - job:
        
        steps:
        
        # configuring node
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - task: Npm@1
          inputs:
            command: 'install'
            verbose: true
            workingDir: '$(workingDir)'
          displayName: 'Install npm package'

        # validating artifacts
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build validate $(workingDir) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryName)'
            workingDir: '$(workingDir)'
          displayName: 'Validate'

        # generating ARM Templates from source code
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build export $(workingDir) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryName) artifacts'
            workingDir: '$(workingDir)'
          displayName: 'Generate ARM template'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(workingDir)/artifacts'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)/application' 
          displayName: 'Copying application artifact'

        # building bicep into ARM
        - task: AzureCLI@2  
          displayName: 'Build bicep artifact' 
          inputs: 
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'  
            scriptLocation: 'inlineScript'  
            inlineScript: |
              $file = "$(Build.SourcesDirectory)/azuredatafactory/iac/datafactory.bicep"            
              New-Item -ItemType Directory -Force -Path $(build.artifactstagingdirectory)/infrastructure
              az bicep build --file $file --outdir $(build.artifactstagingdirectory)/infrastructure

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(build.artifactstagingdirectory)'
            artifact: 'datafactory'
            publishLocation: 'pipeline'

  - stage: 'development'
    displayName: 'Development deploy'
    dependsOn: build
    variables:
      resourceGroupName: $(resourceGroupPartialName)-dev
      dataFactoryName: $(dataFactoryPartialName)-dev
    jobs: 
    - deployment: DeployToDevelopment
      pool:
        vmImage: 'windows-latest'
      environment: dev 
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
                inputs:
                  source: 'current'
                  path: '$(Pipeline.Workspace)'

              - task: AzureResourceManagerTemplateDeployment@3
                displayName: Creating ADF Infrastructure by IaC
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: '$(serviceConnection)'
                  subscriptionId: '$(subscriptionId)'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(resourceGroupName)'
                  location: '$(location)'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)\datafactory\infrastructure\datafactory.json'
                  overrideParameters: -dataFactoryName $(dataFactoryName) -environment development
                  deploymentMode: 'Incremental'
                  deploymentOutputs: 'ArmOutputs'

  - stage: prd
    displayName: Production deploy
    dependsOn: development
    variables:
      resourceGroupName: $(resourceGroupPartialName)-prd
      dataFactoryName: $(dataFactoryPartialName)-prd
    jobs: 
    - deployment: DeployToPRD
      pool:
        vmImage: 'windows-latest'
      environment: prd
      strategy:
        runOnce:
          preDeploy:
            steps:
              - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
                inputs:
                  source: 'current'
                  path: '$(Pipeline.Workspace)'

              - task: AzureResourceManagerTemplateDeployment@3
                displayName: Creating ADF Infrastructure by IaC
                inputs:
                  deploymentScope: "Resource Group"
                  azureResourceManagerConnection: $(serviceConnection)
                  subscriptionId: $(subscriptionId)
                  action: "Create Or Update Resource Group"
                  resourceGroupName: "$(resourceGroupName)"
                  location: "$(location)"
                  templateLocation: "Linked artifact"
                  csmFile: '$(Pipeline.Workspace)\datafactory\infrastructure\datafactory.json'
                  deploymentMode: "Incremental"
                  deploymentOutputs: "ArmOutputs"
                  overrideParameters: -dataFactoryName $(dataFactoryName) -environment production

          deploy:
            steps:
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploying ADF Artificats'
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: $(serviceConnection)
                  subscriptionId: $(subscriptionId)
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(resourceGroupName)'
                  location: '$(location)'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
                  csmParametersFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateParametersForFactory.json'
                  overrideParameters: '-factoryName $(dataFactoryName)  -dataFactory_properties_globalParameters_AzureStorageName_value "redscusstgadfdemo01prd"'
                  deploymentMode: 'Incremental'