# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
    - logicapps-standard

pool:
  vmImage: ubuntu-latest

variables:
  ARCHIVE_FOLDER: 'zip'
  IAC_FOLDER: 'iac'
  SERVICE_CONNECTION: 'QuickStartTemplates-AzureServiceConnection'
  LOGIC_APP_NAME: 'red-scus-statelessdemo-la'
  RESOURCE_GROUP_NAME: 'red-scus-logicappdemo-rg'
  LOCTION_NAME: 'southcentralus'
  LASTD_TEMPLATE_FILE_LOCATION: '$(IAC_FOLDER)/logic-app-std.bicep'

stages:
- stage: Build
  displayName: Build and create artifact
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: CopyFiles@2
      displayName: Copy Source Files to Archive
      inputs:
        Contents: |
          **/logicapps-standard/*
          !.*/**/*
          !.*
          !azure-pipelines*
          !**/iac/**/*
        TargetFolder: $(ARCHIVE_FOLDER)

    # Archive everything in the 'zip' folder
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(ARCHIVE_FOLDER)
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: 'StdLogicApp'
        publishLocation: 'pipeline'

- stage: DevDeploy
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - deployment: 'DeploytoDev'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: AzureCLI@2
              inputs:
                azureSubscription: $(SERVICE_CONNECTION)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  echo '$(Pipeline.Workspace)'
                  ls -ltra $(Pipeline.Workspace)
                  echo '$(Pipeline.Workspace)/logicapps-standard'
                  ls -ltra $(Pipeline.Workspace)/logicapps-standard
                  echo '$(System.DefaultWorkingDirectory)'
                  ls -ltra $(System.DefaultWorkingDirectory)
                  ls -ltra $(Build.SourcesDirectory)/logicapps-standard/iac
                  az --version
                  az group create --name $(RESOURCE_GROUP_NAME)-dev --location $(LOCTION_NAME)
                  az deployment group create --resource-group $(RESOURCE_GROUP_NAME)-dev --template-file $(Pipeline.Workspace)/logicapps-standard/iac/logic-app-std.bicep

            - task: AzureFunctionApp@1  
              inputs:
                azureSubscription: $(SERVICE_CONNECTION)
                appType: 'workflowapp'
                appName: $(LOGIC_APP_NAME)-dev
                package: '$(System.ArtifactsDirectory)/*.zip'
                deploymentMethod: 'zipDeploy'


- stage: ProdDeploy
  displayName: Deploy to Prod
  dependsOn: DevDeploy
  jobs:
  - deployment: 'DeploytoDev'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'StdLogicApp'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: AzureFunctionApp@1  
              inputs:
                azureSubscription: $(SERVICE_CONNECTION)
                appType: 'workflowapp'
                appName: $(LOGIC_APP_NAME)-prd
                package: '$(System.ArtifactsDirectory)/*.zip'
                deploymentMethod: 'zipDeploy'