name: Auto-comment GH Script
on:
  issues:
    types: [opened]
jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new issue
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Thank you for creating an issue!  Someone will respond as soon as they can."
            });
    - name: Add issue to project board
      uses: actions/add-to-project@v0.3.0
      with:
        project-url: https://github.com/users/anotherRedbeard/projects/3
        github-token: ${{secrets.CR_PAT}}
        labeled: bug
